environment:
  R_INSTALL_DIR: 'C:\ProgramData\R\'
  R_TOOLS_INSTALL_DIR: 'C:\ProgramData\RTools\'

version: '7.5.0.{build}'

branches:
  only:
    - develop

skip_tags: true

pull_requests: 
  do_not_increment_build_number: true     

skip_commits:
  files:
    - '*.md'

install:
  - set PATH=C:\Ruby22\bin;%R_INSTALL_DIR%bin\x64;%R_TOOLS_INSTALL_DIR%bin;%PATH%
  - git submodule update --init --recursive
  - ps: >-
      (new-object net.webclient).DownloadFile('https://cran.r-project.org/bin/windows/base/old/3.5.2/R-3.5.2-win.exe', 'C:\R.exe')

      Start-Process C:\R.exe -ArgumentList /VERYSILENT, /DIR=$env:R_INSTALL_DIR -Wait
  - ps: >-
      (new-object net.webclient).DownloadFile('https://cran.r-project.org/bin/windows/Rtools/Rtools35.exe', 'C:\\Rtools.exe')

      Start-Process C:\Rtools.exe -ArgumentList /VERYSILENT, /DIR=$env:R_TOOLS_INSTALL_DIR -Wait      

before_build:
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser 
  - nuget sources add -name simmodel -source https://ci.appveyor.com/nuget/ospsuite-simmodel
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes-282
  - nuget restore -PackagesDirectory packages

build_script:
  - rake "create_setup[%APPVEYOR_BUILD_VERSION%]"
  - 7z a setup.zip %APPVEYOR_BUILD_FOLDER%\setup\deploy\*.msi

artifacts:
  - path: '*.zip'  
    name: 'package'

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=
    
