# Perform unit tests for the R Toolbox.
# Usage from CMD: Rpackage DoRUnitTesting.R "Path/To/The/ToolboxFolder"

library(RUnit)
#library(codetools)
library(MoBiToolboxForR, quietly=TRUE)

main = function() {
    # Get the arguments passed via CLI. A path to the (uncompiled) toolbox can be supplied. Otherwise, a default path defined in the script will be used.
    args = commandArgs(trailingOnly = TRUE)

    # Default path to the toolbox. Selected if no path provided via CLI.
    toolboxDir = "";
    # Path to the directory where test files are located.
    testFolderDir = paste0(toolboxDir, "tests");
    # Path to the directory where toolbox source files are located.
    srcFolderDir = paste0(toolboxDir, "src/code");
    #Path to the *.html file for writing test results.
    htmlFileName = paste0(testFolderDir, "/Protocol.html");
    testSuiteName = "MoBiToolBoxForRTests";

    if (length(args) > 0) {
        toolboxDir = args[1];
        if (length(args) > 1) {
            warning("The function only supports one command line parameter, which is the path to the toolbox location. In case of multiple parameters, only the first one is used as a path, the others are ignored.")
        }
    }

    setwd(toolboxDir)
    options <- getOption("RUnit")
    options$silent <- TRUE
    options("RUnit" = options)

    #Tracking the number of errors and failures generated by the tests.
    nrOfErrors = 0;

    #Source all code files of the toolbox.
    rfiles <- dir(srcFolderDir, pattern = "*.R")
    for (i in 1:length(rfiles)) {
        rfile <- file.path(srcFolderDir, rfiles[i])
        if (!(file.info(rfile)$isdir)) {
            source(rfile)
        }
    }

    myTestSuite <- defineTestSuite(name = testSuiteName, dirs = testFolderDir, testFileRegexp = "^runit.+\\.R")
    testResults <- runTestSuite(testSuites = myTestSuite, useOwnErrorHandler = TRUE)

    errors = getErrors(testResults);
    nrOfErrors = errors$nErr + errors$nFail;

    # Print test protocol into the command line.
    printTextProtocol(testResults)

    #Print test protocol into a html.
    printHTMLProtocol(testResults, fileName=htmlFileName)
    # Repair href Links:
    protocol.html = scan(file = htmlFileName, what = character(0))
    protocol.html = gsub('href=\"', 'href=\"file://', protocol.html)
    protocol.html = gsub('Basis', 'Basis%20', protocol.html)
    write(protocol.html, htmlFileName)

    #Not sure what this line is for.
    #checkUsagePackage("MoBiToolboxForR")
    
    print(nrOfErrors)
    return(nrOfErrors)
}

main();